version: '2'

services:
  scripts:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./:/home/python/lab01"
    environment:
      TOKEN: "???"
      API_URL: "https://api.github.com/graphql"